apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-install
spec:
  steps:
    - name: install
      image: node:16
      command: [npm]
      args: [install]
      workingDir: /workspace/source
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-jasmine
spec:
  steps:
    - name: test
      image: node:16
      command: [npx]
      args: [jasmine]
      workingDir: /workspace/source
